name: Build&Test

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        os:  [ ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - run: ./gradlew check
        env:
          KEY_VERSION: ${{ matrix.key }}

      - uses: actions/upload-artifact@v7
        with:
          name: Reports-${{ matrix.os }}-${{ matrix.key }}
          path: build/reports


      - run: python scripts/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml src/main/java > cov-report.xml
        if: success() || failure()

      - name: Upload coverage report
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          file: cov-report.xml
          language: Java
          label: code-coverage/jacoco-${{matrix.os}}-${{matrix.jdk}}

      - name: Upload Coverage Report
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: aggregated-coverage
          path:  build/reports/jacoco/test/html/
          compression-level: '9'
          retention-days: 7

      - name: Test reporting
        uses: dorny/test-reporter@v3
        if: success() || failure()
        with:
          name: Test Report
          path: "build/test-results/test/*.xml"
          reporter: java-junit
